#!/bin/bash
###########################################################################
# Configuration of the tunN devices for usage with Basilisk II.
# (derived MOL tunconfig script)
#
# This script should be named /usr/share/BasiliskII/tunconfig (unless
# the default name has been changed with the 'etherconfig' keyword).
#
#       Usage:          tunconfig iface up|down
#
# If the linux box is configured as a firewall, the rules below might
# need some adjustments.
#
# The IP Tunnel driver requires IP forwarding to be enabled. Run as root:
#
#       echo 1 >/proc/sys/net/ipv4/ip_forward
#
###########################################################################

set -e

SUDO=/usr/bin/sudo
BRCTL=/sbin/brctl
IFCONFIG=/sbin/ifconfig
IPTABLES=/sbin/iptables

BRIDGE_DEV=br0
TUN_DEV=$1
ACTION=$2

[[ $# = 2 ]] || {
	echo "Usage: tunconfig iface up|down"
    exit 2
}

[[ "`id -u`" = "0" ]] && {
    SUDO=""
}

set -x

[[ "$ACTION" = up ]] && {
	$SUDO $BRCTL addif $BRIDGE_DEV $TUN_DEV
	$SUDO $IFCONFIG $TUN_DEV up
}

[[ "$ACTION" = down ]] && {
	$SUDO $IFCONFIG $TUN_DEV down
    $SUDO $BRCTL delif $BRIDGE_DEV $TUN_DEV
}
