#define ENABLE_DYNGEN 0
#define HAVE_CEIL 1
#define HAVE_CEILF 1
//#define HAVE_EXP2 1
//#define HAVE_EXP2F 1
#define HAVE_FLOOR 1
#define HAVE_FLOORF 1
#define HAVE_INTTYPES_H 1
//#define HAVE_LOG2 1
//#define HAVE_LOG2F 1
#define HAVE_MEMORY_H 1
#define HAVE_SIGSEGV_SKIP_INSTRUCTION 1
#define HAVE_STDLIB_H 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
//#define HAVE_TRUNC 1
//#define HAVE_TRUNCF 1
#define HAVE_WIN32_EXCEPTIONS 1
#define HAVE_WIN32_VM 1
#define PACKAGE_BUGREPORT "Christian.Bauer@uni-mainz.de"
#define PACKAGE_NAME "SheepShaver"
#define PACKAGE_STRING "SheepShaver 2.3"
#define PACKAGE_TARNAME "SheepShaver"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "2.3"
#define SIZEOF_DOUBLE 8
#define SIZEOF_FLOAT 4
#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_VOID_P 4
#define STDC_HEADERS 1
#define USE_SDL 1
#define USE_SDL_AUDIO 1
#define USE_SDL_VIDEO 1
